Footer
Irrreny/Project_KMarketer pull request #7
Opened 2023-08-30 13:50 UTC by Irrreny

Ivan, i remember you said you want to make footer page with us today, but i wanted to try to make it by myself first.
So here is the screenshot (remember, its just a try :) )
![image](https://github.com/Irrreny/Project_KMarketer/assets/141719439/2a46d88f-2105-4d1d-9848-c8302fb8e06c)

2023-08-30 13:59 UTC, IvanCeban commented
WoW!

2023-08-30 15:25 UTC, IvanCeban reviewed
Wow! I'm impressed! Great job!
Let me do the code review after today's Lesson, but I bet there will be not much to comment here.

2023-08-30 16:28 UTC, Irrreny commented
I did it completely different though, so looking forward to your comments :)

2023-09-01 07:51 UTC, IvanCeban requested changes
Great code structure and good namings!
Please pay more attention to content alignment (I mean use container for any section content)

Also avoid fixed sizes. Always keep in mind that your website should be responsive

2023-09-01 07:51 UTC, IvanCeban commented on index.html
>             .call-to-action {
good naming for button. I see you did some research about it

2023-09-01 07:51 UTC, IvanCeban commented on index.html
> +        <section class="footer">
use a semantic `<footer>` tag for footer

2023-09-01 07:51 UTC, IvanCeban commented on index.html
> +            <div class="footer-header">
Please pay attention that according the design footer content is aligned with the rest of the sections content. 
So I highly recommend you to wrap all footer content into a `container` same as the content of all the pages. 
You've set up padding 195px everywhere, but this is not flexible solution.

2023-09-01 07:51 UTC, IvanCeban commented on index.html
> +            grid-template-columns: repeat(3,328px);
Do not set fixed size to your cards. Let them take as much space as they can. Limit only max width of the container

2023-09-01 07:51 UTC, IvanCeban commented on index.html
> +                    <p style="font-size: 12px; color: #BDBDBD; margin: 0;">Please insert your email</p>
inline style :(

2023-09-01 07:51 UTC, IvanCeban commented on index.html
> +                    <input type="email" class="footer-email" name="email" placeholder="Your Email" pattern="[a-zA-Z0-9._%+-]+@[a-z0-9.-]+\.[a-zA-Z]{2,4}" required>
Would be better to wrap your input and button into a form

2023-09-01 09:19 UTC, closed without merging